### ISSUE TITLE
Duplicate Entry

### ISSUE THREAD

**Issue by BenTen** [DannyCooper/knowledge-base-cpt#1]
Hello,

I tried to use your plugin on WP 4.9.4

I installed your plugin
Create three sections and three articles.

- KB 1 in Test 1
- KB 2 in Test 2
- KB 3 in Test 3

I follow that tuto to copy-past the function: http://www.wpbeginner.com/wp-tutorials/how-to-create-a-wiki-knowledge-base-using-wordpress/
```
function wpb_knowledgebase() {
    // Get Knowledge Base Sections
    $kb_sections = get_terms('section','orderby=name&hide_empty=0');
    // For each knowledge base section
    foreach ($kb_sections as $section) :
    $return .= '<div class="kb_section">';
    // Display Section Name
    $return .= '<h4 class="kb-section-name"><a href="'. get_term_link( $section ) .'" title="'. $section->name .'" >'. $section->name .'</a></h4><ul class="kb-articles-list">';
     
    // Fetch posts in the section
    $kb_args = array(
        'post_type' => 'knowledge_base',
        'posts_per_page'=>-1,
        'tax_query' => array(
            array(
                'taxonomy' => 'section',
                'terms'    => $section,
            )       ,
        ),
    );
     
    $the_query = new WP_Query( $kb_args );
        if ( $the_query->have_posts() ) : 
            while ( $the_query->have_posts() ) : $the_query->the_post(); 
                $return .=  '<li class="kb-article-name">';
                $return .=  '<a href="'. get_permalink( $the_post->ID ) .'" rel="bookmark" title="'. get_the_title( $the_post->ID ) .'">'. get_the_title( $the_post->ID ) .'</a>';
                $return .=  '</li>';
            endwhile; 
    wp_reset_postdata(); 
         else : 
                $return .= '<p>No Articles Found</p>';
        endif; 
    $return .=  '</ul></div>';
    endforeach;
    return $return;
}
// Create shortcode 
add_shortcode('knowledgebase', 'wpb_knowledgebase');
```

But a the end, I can see there is duplicate entry in the page with the shortcode [knowledgebase]
![test](https://user-images.githubusercontent.com/915869/36349645-845bbdfe-14ce-11e8-87f7-0ca4bef81282.png)

**Comment by DannyCooper** [comment]
Hi @BenTen,

In the latest version (1.1.0) I've added our own [knowledgebase] shortcode. That means if you remove the wpb_knowledgebase function and keep your shortcode in place it should work correctly now.

Let me know if I can help with anything else.

Thanks!

**Comment by BenTen** [comment]
Hello,
I just try the update (and remove the other functions) but I can see the same issue.

**Comment by DannyCooper** [comment]
That shouldn't happen unless KB 2 has been placed in multiple sections. If you'd like to send me a wp-admin login to email@dannycooper.com I will look into it for you.

**Comment by BenTen** [comment]
I sent an email with access.

Thank you so much

**Comment by DannyCooper** [comment]
Hi Ben,

It appears some other code or plugin is skewing the output. If you have a development or staging version of your website I recommend testing with all other plugins/custom code disabled.

**Comment by BenTen** [comment]
ho?! 
It will be hard to found the wrong code but thank you for your help :)
